Repository alexis-menendez/Inner-Orbit, pull requests merged in 2025-05, with the labels that each got.

#70 worked out some kinks with the constellation logic
  client/src/components/journal/Constellation.tsx
Labels: frontend

#72 Render updates
  README.md
  server/package.json
  server/src/controllers/journalController.ts
  server/src/schema/resolvers.ts
  server/src/server.ts
  server/tsconfig.json
Labels: backend

#88 Debugged and Refactored Tracker to be consistent with auth use (use like the rest of the site) and use modular css
  Tracker.md
  client/package-lock.json
  client/src/apolloClient.ts
  client/src/assets/css/tracker/Tracker.module.css
  client/src/components/dashboard/WeeklyMoodCalendar.tsx
  client/src/components/home/LoginForm.tsx
  client/src/components/home/RegisterForm.tsx
  client/src/components/tracker/CreateMood.tsx
  client/src/components/tracker/MoodCalendar.tsx
  client/src/components/tracker/MoodModal.tsx
  client/src/components/tracker/MoodSelector.tsx
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/models/Mood.ts
  client/src/models/User.ts
  client/src/pages/Dashboard.tsx
  client/src/pages/Home.tsx
  client/src/pages/Tracker.tsx
  instructions/file-tree.md
  notes.md
  server/src/controllers/trackerController.ts
  server/src/controllers/userController.ts
  server/src/models/Tracker.ts
  server/src/models/User.ts
  server/src/schema/resolvers.ts
  server/src/schema/typeDefs.ts
  server/src/server.ts
  server/src/utils/formatEntry.ts
  server/src/utils/trackerColors.ts
Labels: bug, backend
